# Generated by Django 3.1.2 on 2020-10-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('win', models.BooleanField(null=True)),
                ('quantity', models.IntegerField()),
                ('average', models.DecimalField(decimal_places=2, max_digits=12)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.scenario')),
            ],
        ),
    ]
