# Generated by Django 3.1.2 on 2020-10-25 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('answer', models.CharField(max_length=500)),
                ('weight', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('next_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_answers', to='app.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.question')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.scenario')),
            ],
        ),
    ]
