# Generated by Django 3.1.2 on 2020-11-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201028_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quantity',
            new_name='times_chosen',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='win',
            new_name='is_winning',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quantity',
            new_name='times_lost',
        ),
        migrations.RemoveField(
            model_name='question',
            name='average',
        ),
        migrations.AddField(
            model_name='question',
            name='times_showed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
