# Generated by Django 3.1.2 on 2020-11-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201108_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='availability',
            field=models.IntegerField(default=95),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='business',
            field=models.IntegerField(default=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='defence',
            field=models.IntegerField(default=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='other',
            field=models.IntegerField(default=47),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='reports',
            field=models.IntegerField(default=95),
            preserve_default=False,
        ),
    ]
