# Generated by Django 3.1.2 on 2020-11-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201112_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='role_level',
            name='points_from',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role_level',
            name='points_to',
            field=models.DecimalField(decimal_places=5, default=2, max_digits=7),
            preserve_default=False,
        ),
    ]
