# Generated by Django 3.1.2 on 2020-11-13 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201112_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='app.role_level'),
            preserve_default=False,
        ),
    ]
