# Generated by Django 3.1.2 on 2020-11-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201114_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='received_points',
            new_name='dd',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='weight',
        ),
    ]
