# Generated by Django 3.1.2 on 2020-11-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_game_dd'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='report',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
