# Generated by Django 3.1.2 on 2020-12-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_game_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='competence_list', to='app.Role'),
        ),
    ]
