# Generated by Django 3.1.2 on 2020-12-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_competence_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='competences', to='app.Role'),
        ),
    ]
