# Generated by Django 3.1.2 on 2020-12-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20201211_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.role_level'),
        ),
    ]
