# Generated by Django 3.1.2 on 2020-12-16 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20201214_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='role_scenarios', to='app.role'),
            preserve_default=False,
        ),
    ]
