# Generated by Django 3.1.2 on 2020-12-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_scenario_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='roles',
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.role'),
        ),
    ]
