# Generated by Django 3.1.2 on 2020-12-30 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20201230_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_competence_achieved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='competence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.competence'),
        ),
    ]
