# Generated by Django 3.1.2 on 2020-12-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_game_competences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='report',
        ),
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
